---
- name: Get Token
  command: cat /var/lib/rancher/k3s/server/node-token
  register: token
  delegate_to: "{{ groups['master'][0] }}"

- name: Join to Kubernetes cluster
  shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ token.stdout }} sh -s - --node-ip {{ ansible_default_ipv4.address }}
