---
- name: "Create containerd.conf"
  copy:
    src: "containerd.conf"
    dest: "/etc/modules-load.d/"
    mode: 0644

- name: "Create 99-kubernetes-cri.conf"
  copy:
    src: "99-kubernetes-cri.conf"
    dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
    mode: 0644

- name: Read values from all system directories
  shell: sysctl --system

- name: Install containerd
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - containerd

- name: "Create containerd config directory"
  file:
    path: "/etc/containerd"
    state: directory
    mode: 0755

# - name: "Generate containerd config file"
#  shell: containerd config default | tee /etc/containerd/config.toml

- name: "Create /etc/containerd/config.toml"
  copy:
    src: "config.toml"
    dest: "/etc/containerd/config.toml"
    mode: 0644

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
    enabled: yes
