---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Copy Kubeadm Configuration
  template:
    src: kubeadm-config.yaml.j2
    dest: "/etc/kubernetes/kubeadm-config.yaml"  

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --config "/etc/kubernetes/kubeadm-config.yaml" \
                 --upload-certs \
                 --ignore-preflight-errors=swap
  register: init_cluster

- name: Generate certificate key
  command: kubeadm init phase upload-certs --upload-certs
  register: init_upload_certs

- name: Set fact certificate key
  set_fact: certificate_key={{ init_upload_certs.stdout_lines[2] }}

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true
