---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: metrics-server

- name: "Copy yaml file"
  copy:
    src: "components.yaml"
    dest: "{{ tmp_dir }}/components.yaml"
    mode: 0644
  tags: metrics-server

- name: "Deploy metrics-server"
  shell: "kubectl apply -f {{ tmp_dir }}/components.yaml --kubeconfig={{ kubeadmin_config }}"
  tags: metrics-server

