---
- name: Starting k3s server
  shell: curl -sfL https://get.k3s.io | sh -s - --tls-san {{ control_plane_endpoint_ip }} --node-ip {{ ansible_default_ipv4.address }}

- name: "Copy kubeconfig file"
  command: cp /etc/rancher/k3s/k3s.yaml /etc/rancher/k3s/admin.conf

- name: "Replace URL"
  replace: >-
    dest='/etc/rancher/k3s/admin.conf'
    regexp='https://127.0.0.1:6443'
    replace='https://{{ control_plane_endpoint_ip }}:6443'

- name: "Copy config file"
  fetch:
    src: /etc/rancher/k3s/admin.conf
    dest: "{{ lookup('env', 'HOME') }}/admin.conf"
    flat: yes
  run_once: yes
  ignore_errors: yes
